FROM node:18-alpine AS installer
RUN corepack enable && corepack prepare pnpm@latest --activate

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

ARG NEXTAUTH_SECRET
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET

WORKDIR /app

COPY ./formbricks .
RUN pwd
RUN ls -la
RUN touch ./apps/web/.env


RUN pnpm install
RUN pnpm post-install

CMD npx prisma generate; \
    pnpm dlx prisma migrate deploy; \
    pnpm run dev;